name: Automatic Data Update

on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * *'

jobs:
  DataUpdater:
    name: Automatic Data Update
    runs-on: ubuntu-latest
    if: github.repository_owner == 'sapphiredev'
    steps:
      - name: Checkout Project
        uses: actions/checkout@v4
      - name: Install dependencies
        uses: sapphiredev/.github/actions/install-yarn-dependencies@main
        with:
          node-version: 20
      - name: Run plugin-api MIME type sync
        run: yarn sync-mime-types
      - name: Run prettier on the code
        run: yarn format
      - name: Configure Git
        run: |
          git remote set-url origin "https://${GITHUB_TOKEN}:x-oauth-basic@github.com/${GITHUB_REPOSITORY}.git"
          git config --local user.email "${GITHUB_EMAIL}"
          git config --local user.name "${GITHUB_USER}"
        env:
          GITHUB_USER: github-actions[bot]
          GITHUB_EMAIL: 41898282+github-actions[bot]@users.noreply.github.com
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Commit any changes
        run: |
          git add .;
          if git diff-index --quiet HEAD --; then
            echo "No changes to commit, exiting with code 0"
            exit 0;
          else
            git commit -sam "feat: update mime types";
            git push --set-upstream origin $(git rev-parse --abbrev-ref HEAD)
          fi
