name: Continuous Delivery

on:
  workflow_run:
    workflows: ['Automatic Data Update']
    types:
      - completed
    branches:
      - main

jobs:
  PublishPackage:
    name: Publish @sapphire/iana-mime-types
    uses: sapphiredev/.github/.github/workflows/reusable-publish.yml@main
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    with:
      project-name: '@sapphire/iana-mime-types'
      build: true
    secrets:
      NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
      SKYRA_TOKEN: ${{ secrets.SKYRA_TOKEN }}
