name: Continuous Delivery

on:
  push:
    branches:
      - main
    paths:
      - src/

jobs:
  PublishPackage:
    name: Publish @sapphire/iana-mime-types
    uses: sapphiredev/.github/.github/workflows/reusable-publish.yml@main
    with:
      project-name: '@sapphire/iana-mime-types'
      build: true
    secrets:
      NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
      SKYRA_TOKEN: ${{ secrets.SKYRA_TOKEN }}
