name: Continuous Delivery
run-name: Publish @sapphire/iana-mime-types

on:
  workflow_run:
    workflows: ['Automatic Data Update']
    types:
      - completed
    branches:
      - main

permissions:
  id-token: write
  contents: write

jobs:
  PublishPackage:
    name: Publish @sapphire/iana-mime-types
    uses: sapphiredev/.github/.github/workflows/reusable-publish.yml@main
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    with:
      project-name: '@sapphire/iana-mime-types'
      build: true
    secrets:
      SKYRA_TOKEN: ${{ secrets.SKYRA_TOKEN }}
